server:
  port: 8080

run:
  basic:
    first-api-url: [First API Server]
    auth-target-url: [Second API Server]
    test-count:
      limit: 100000

spring:
  apitestdb:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apitestdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: [user_db_name]
    password: [user_db_password]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/apitestdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: [user_db_name]
    password: [user_db_password]
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    generate-ddl: true
    show-sql: true
